name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get inputs
      run: |
        for i in {1..25}; do ./get_input.sh $i; done
      env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
    - name: make
      run: make
    - name: run
      run: |
        ./d01.out < test/resources/day01.in
